[input]
middle_click_paste = true
window_drag_toggle = "none"

[input.keyboard]
layout = ""
variant = ""
options = ""
repeat_rate = 25
repeat_delay = 600
numlock_toggle = true
track_layout = "global"

[input.touchpad]
tap = true

[input.mouse]
sensitivity = 0.0
scroll_wheel_step = 60

[input.tablet]
enabled = true

[input.cursor]
theme = ""
size = 24
hardware_cursor = true
follows_focus = false
hide_when_typing = false
hide_timeout_ms = 0

[input.focus]
follows_mouse = false

# [[input.device]]
# name = "Acme Split Keyboard"
# layout = "us"
# variant = "colemak_dh"
# repeat_rate = 40
# repeat_delay = 250

# [[input.device]]
# name = "Acme Precision Touchpad"
# tap = true
# natural_scroll = false
# accel_profile = "flat"
# sensitivity = 0.0
# disable_while_typing = false
# click_method = "clickfinger"

# [[input.device]]
# name = "Acme Gaming Mouse"
# accel_profile = "flat"
# sensitivity = 0.0
# scroll_button = "MouseBack"
# scroll_button_lock = false
