[customizations.installer.kickstart]
contents = """
timezone Europe/Vienna --utc
keyboard --xlayouts=us,de --switch=grp:alt_shift_toggle

%post
bootc switch --mutate-in-place --transport registry ghcr.io/realfriesi/xit-os:latest

flatpak install --system --noninteractive flathub \
  io.github.kolunmi.Bazaar \
  com.danklinux.dankcalendar \
  app.zen_browser.zen \
  org.gnome.baobab \
  org.gnome.Calculator \
  org.gnome.gitlab.somas.Apostrophe \
  org.gnome.Loupe \
  org.gnome.Papers \
  com.usebottles.bottles \
  app.drey.KeyRack \
  org.gnome.TextEditor \
  com.github.tchx84.Flatseal \
  it.mijorus.gearlever
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]

disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription",
]
