#!/bin/bash

set -euo pipefail

FEDORA_VERSION="$(rpm -E '%{fedora}')"

dnf5 config-manager addrepo --from-repofile="https://copr.fedorainfracloud.org/coprs/lionheartp/Hyprland/repo/fedora-${FEDORA_VERSION}/lionheartp-Hyprland-fedora-${FEDORA_VERSION}.repo"
dnf5 config-manager setopt copr:copr.fedorainfracloud.org:lionheartp:Hyprland.enabled=0

dnf5 config-manager addrepo --from-repofile="https://copr.fedorainfracloud.org/coprs/avengemedia/danklinux/repo/fedora-${FEDORA_VERSION}/avengemedia-danklinux-fedora-${FEDORA_VERSION}.repo"
dnf5 config-manager setopt copr:copr.fedorainfracloud.org:avengemedia:danklinux.enabled=0

# Stable DMS instead of dms-git: the stable RPM ships the matugen templates on
# disk (/usr/share/quickshell/dms/matugen), while dms-git only embeds them in
# the binary and unpacks them to $XDG_RUNTIME_DIR at runtime.
dnf5 config-manager addrepo --from-repofile="https://copr.fedorainfracloud.org/coprs/avengemedia/dms/repo/fedora-${FEDORA_VERSION}/avengemedia-dms-fedora-${FEDORA_VERSION}.repo"
dnf5 config-manager setopt copr:copr.fedorainfracloud.org:avengemedia:dms.enabled=0

dnf5 install -y \
	--enablerepo=copr:copr.fedorainfracloud.org:lionheartp:Hyprland \
	--enablerepo=copr:copr.fedorainfracloud.org:avengemedia:danklinux \
	--enablerepo=copr:copr.fedorainfracloud.org:avengemedia:dms \
	--exclude=wofi \
	--exclude=nwg-panel \
	hyprland \
	hyprland-guiutils \
	hyprqt6engine \
	xdg-desktop-portal-gtk \
	xdg-desktop-portal-hyprland \
	dms \
	dgop \
	matugen \
	material-symbols-fonts \
	cava \
	ghostty \
	dms-greeter \
	greetd \
	adw-gtk3-theme \
	qt6ct \
	qt6-qtmultimedia \
	qt6-qtsvg \
	qt6-qtimageformats \
	kf6-kimageformats \
	dbus-tools \
	gnome-keyring \
	gnome-keyring-pam \
	accountsservice

# The hyprland.lua generated by DMS calls dbus-update-activation-environment on
# startup; without it the user manager never learns WAYLAND_DISPLAY and
# dms.service starts into a broken session.
command -v dbus-update-activation-environment >/dev/null

# adw-gtk3 and adw-gtk3-dark must both exist system-wide: DMS copies them into
# ~/.local/share/themes on the first theme apply and patches them in place.
for theme in adw-gtk3 adw-gtk3-dark; do
	if [[ ! -d "/usr/share/themes/${theme}/gtk-3.0" ]]; then
		printf 'Missing GTK theme /usr/share/themes/%s/gtk-3.0\n' "${theme}" >&2
		exit 1
	fi
done

systemctl enable greetd.service
systemctl set-default graphical.target
